version: "3.7"

services:

  blog:
    build: .
    container_name: okta-cli-site
    ports:
    - 4000:4000
    volumes:
    - ./:/app
    entrypoint:
    - bundle
    - exec
    - jekyll
    - serve
    - --livereload
    - --host=0.0.0.0
